### ISSUE TITLE
different sep in write_abundance and read_abundance

### ISSUE THREAD

**Issue by mingzhi** [snayfach/PhyloCNV#2]
Cluster results are written as tab separated, but in read_abundance, sep is not specified, which will cause some parsing problems as species_name contains space.

Here is the complain when running the example:
Traceback (most recent call last):
  File "../scripts/run_phylo_cnv.py", line 534, in <module>
    run_program(program, args)
  File "../scripts/run_phylo_cnv.py", line 94, in run_program
    genes.run_pipeline(args)
  File "/SOMEWHERE/.local/lib/python2.7/site-packages/phylo_cnv/genes.py", line 220, in run_pipeline
    genome_clusters = species.select_genome_clusters(args)
  File "/SOMEWHERE/.local/lib/python2.7/site-packages/phylo_cnv/species.py", line 226, in select_genome_clusters
    cluster_abundance = read_abundance(args['profile'])
  File "/SOMEWHERE/.local/lib/python2.7/site-packages/phylo_cnv/species.py", line 217, in read_abundance
    dict[values[0]][field[0]] = field[1](value)
ValueError: invalid literal for int() with base 10: 'phocae'

**Comment by snayfach** [comment]
Thanks for finding this. It should be fixed now. Please let me know if you find any other bugs or have any suggestions for improving the software.
